image: ruby:2.3
before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --path vendor/bundle
  - export SECRET_KEY_BASE=`rake secret`
  - RAILS_ENV=test bundle exec rake db:setup

rspec:
  script:
    - bundle exec rspec
  tags:
    - ruby
