inherit_from: .rubocop_todo.yml

# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# if 文の中はに 3 行まで
# Style/GuardClause:
#   MinBodyLength: 3

# selfの利用を許可する
Style/RedundantSelf:
  Enabled: false

# ブロックの前にスペースを入れないことを許可する => あとで修正する？
Style/SpaceBeforeBlockBraces:
  Enabled: false
