
Metrics/AbcSize:
  Max: 24

Metrics/LineLength:
  Max: 112

Style/AccessModifierIndentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'lib/tasks/unicorn.rake'
    - 'spec/factories/rooms.rb'
    - 'spec/requests/api_spec.rb'


# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/support/shared_db_connection.rb'

# Offense count: 1
Style/ClassVars:
  Exclude:
    - 'spec/support/shared_db_connection.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SingleLineConditionsOnly.
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/rooms_controller.rb'
    - 'app/models/room.rb'









# Offense count: 15
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
# SupportedStyles: ruby19, ruby19_no_mixed_keys, hash_rockets
# Style/HashSyntax:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
# Style/IfUnlessModifier:
#   Exclude:
#     - 'config/unicorn/development.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
# Style/IndentHash:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: normal, rails
# Style/IndentationConsistency:
#   Exclude:
#     - 'app/apis/api.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: Width.
# Style/IndentationWidth:
#   Exclude:
#     - 'app/apis/api.rb'
#     - 'app/models/room.rb'
#     - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
# Style/MethodDefParentheses:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Style/MultilineBlockLayout:
#   Exclude:
#     - 'spec/factories/rooms.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Style/NumericLiterals:
#   MinDigits: 15

# Offense count: 1
# Cop supports --auto-correct.
# Style/RedundantBegin:
#   Exclude:
#     - 'lib/tasks/unicorn.rake'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
# Style/RedundantReturn:
#   Exclude:
#     - 'app/models/room.rb'

# Offense count: 12
# Cop supports --auto-correct.
# Style/RedundantSelf:
#   Exclude:
#     - 'app/models/match.rb'
#     - 'app/models/room.rb'
#     - 'app/models/user.rb'

# Offense count: 55
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
# Style/SpaceBeforeBlockBraces:
#   Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
# Style/SpaceInsideHashLiteralBraces:
#   Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    # - 'app/apis/api.rb'
    # - 'app/models/match.rb'
    # - 'spec/controllers/rooms_controller_spec.rb'

# Offense count: 325
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 34
# Cop supports --auto-correct.
Style/Tab:
  Exclude:
    - 'app/apis/api.rb'
    - 'app/models/room.rb'
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: final_newline, final_blank_line
Style/TrailingBlankLines:
  Exclude:
    - 'config/initializers/config.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4
